In [1]:
import pandas as pd
import psycopg2
import sqlalchemy

In [2]:
weather=pd.read_csv("../raw_data/Weather.csv")
weather

,Key,TFS_Alarm_Time,Latitude,Longitude,StartTime,EndTime,temp,dwpt,rhum,prcp,snow,wdir,wspd
0,180224210468655994,2018-02-24 21:04:29,43.686558,-79.599419,2018-02-24 21:00:00,2018-02-24 22:00:00,4.0,-3.5,58.0,0.0,0.0,70.0,9.4
1,180224212476613900,2018-02-24 21:24:43,43.766135,-79.390039,2018-02-24 21:00:00,2018-02-24 22:00:00,4.0,-3.1,60.0,0.0,0.0,70.0,13.0
2,180225132974322450,2018-02-25 13:29:59,43.743230,-79.245061,2018-02-25 13:00:00,2018-02-25 14:00:00,4.0,-3.5,58.0,0.0,0.0,70.0,9.4
3,180225141370864780,2018-02-25 14:13:39,43.708659,-79.478062,2018-02-25 14:00:00,2018-02-25 15:00:00,4.4,3.7,95.0,0.7,0.0,60.0,22.3
4,180225182071814431,2018-02-25 18:20:43,43.718118,-79.443184,2018-02-25 18:00:00,2018-02-25 19:00:00,12.5,1.2,46.0,0.0,0.0,220.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25812,210624072873116077,2021-06-24 07:28:16,43.731133,-79.607765,2021-06-24 07:00:00,2021-06-24 08:00:00,17.5,10.8,65.0,0.0,0.0,160.0,8.0
25813,210624075974635881,2021-06-24 07:59:40,43.746315,-79.588165,2021-06-24 07:00:00,2021-06-24 08:00:00,17.5,10.8,65.0,0.0,0.0,160.0,8.0
25814,210624114565703745,2021-06-24 11:45:44,43.657067,-79.374567,2021-06-24 11:00:00,2021-06-24 12:00:00,17.2,12.3,73.0,0.0,0.0,194.0,13.3
25815,210624140466304021,2021-06-24 14:04:07,43.663052,-79.402109,2021-06-24 14:00:00,2021-06-24 15:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25816,210624150774925104,2021-06-24 15:07:19,43.749227,-79.510449,2021-06-24 15:00:00,2021-06-24 16:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
weather= weather.rename(columns={'Key':'weather_key','TFS_Alarm_Time':'datetime',
                                          'Latitude':'latitude','Longitude':'longitude',
                                          'StartTime':'start_time' ,'EndTime':'end_time',
                                          'temp':'temperature', 'dwpt':'dewpoint',
                                          'rhum':'relative_humidity', 'prcp':'precipitaion',
                                          'snow':'snow','wdir':'wind_direction',
                                          'wspd':'wind_speed'
})
weather.drop_duplicates(subset='weather_key', keep='first', inplace=True)

# save to database

engine = sqlalchemy.create_engine('postgresql+psycopg2://postgres:CSI4142@localhost:5432/fire_hazard')
weather.to_sql(name='dim_weather', con=engine,if_exists='append', index=False)

816